USE BasketBallDB;
DROP TABLE IF EXISTS West_Standings;
DROP TABLE IF EXISTS East_Standings;
DROP TABLE IF EXISTS Standard_Standings;
DROP TABLE IF EXISTS Standings;
DROP TABLE IF EXISTS Player;
DROP TABLE IF EXISTS Team;
DROP TABLE IF EXISTS Season;